# Generated by Django 5.0.2 on 2024-02-17 09:28

import uuid

import core.utils
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        default=core.utils.generate_product_code,
                        editable=False,
                        max_length=255,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("price", models.FloatField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
