# Generated by Django 5.0.6 on 2024-06-04 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitems",
            name="amount",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
