# Generated by Django 5.0.2 on 2024-05-20 13:02

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="code",
            field=models.CharField(
                default=core.utils.generate_customer_code,
                editable=False,
                max_length=255,
            ),
        ),
    ]
