# Generated by Django 5.0.6 on 2024-05-23 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0003_customer_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
